language: php

services:
  - docker

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist
  - sudo service mysql stop
  - docker-compose -f ./tests/docker-compose.yml up -d
  - php tests/wait.php

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - docker-compose -f ./tests/docker-compose.yml down